argoproj-labs/argocd-vault-plugin

README.md

Add initial documentation to README #5

docs: Add initial readme documentation

---

README.md
go.mod
pkg/vault/approle.go
pkg/vault/approle_test.go
pkg/vault/config.go
pkg/vault/config_test.go
pkg/vault/secretmanager.go
pkg/vault/secretmanager_test.go
pkg/vault/utils_test.go

Support IBM Secret Manager
**Fixes:** #9 

feat: Support IBM Secret Manager

---

README.md
patch.yaml
pkg/kube/template.go

Make some changes in the Readme to provide more details on how to use the tool.
Also included a rider to use lowercase for the vault path instead of camel case.
Will be `prefix/configmap` instead of `prefix/ConfigMap` now
**Relates To:** #27 

docs: Update readme to include better usage instructions

---

cmd/generate.go
cmd/util.go
pkg/helpers/test_helpers.go
pkg/kube/client.go
pkg/vault/approle.go
pkg/vault/approle_test.go
pkg/vault/client_test.go
pkg/vault/config.go
pkg/vault/config_test.go
pkg/vault/github.go
pkg/vault/github_test.go
pkg/vault/secretmanager.go
pkg/vault/secretmanager_test.go
pkg/vault/util.go
pkg/vault/utils_test.go

Write vault token to a file that can then be read on subsequent runs. Will check the tokens expire date and if expired will re authenticate and write new token.
**Fixes:** #31 

feat: Read/Write vault token to/from file

---

version/version.go

chore: bump version to 0.2.0

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Added a code of conduct and added content to the contributing doc
**Fixes:** #37

docs: Update contributing, add code of conduct

---

README.md

Update example initContainer to contain a step for running chmod on the avp binary
**Fixes:** #45 

docs: Update readme to include chmod of binary

---

Makefile
README.md
pkg/helpers/test_helpers.go
pkg/kube/template.go
pkg/vault/approle.go
pkg/vault/approle_test.go
pkg/vault/client.go
pkg/vault/client_test.go
pkg/vault/config.go
pkg/vault/github.go
pkg/vault/github_test.go
pkg/vault/secretmanager.go
pkg/vault/secretmanager_test.go
pkg/vault/types.go
pkg/vault/util.go
pkg/vault/utils_test.go
version/version.go

These changes allow for the user to specify which kv version to be used. This will now allow us to support kv1 and kv2.
**Fixes:** #42 

feat: Add support for kvv2

---

README.md
cmd/util.go
pkg/vault/util.go
pkg/vault/utils_test.go

Addressing some usability concerns: include `.yml` files and print a helpful error message for kv-v2 users
**Fixes:** #44, #47

fix: Include .yml extension and helpful kvv2 message

---

cmd/root.go

Update usage from `argocd-vault` to `argocd-vault-plugin`

fix: Update usage to be argocd-vault-plugin

---

README.md

Add better usage documentation with examples for each backend/auth combination
**Fixes:** #60 

docs: Update usage to have specific examples for each backend/auth

---

Makefile
README.md
version/version.go

chore: Update version to 0.4.0

---

README.md
examples/annotation-example.yaml
examples/kv-version.yaml
examples/path-prefix.yaml

Update readme to have a table of contents and then add some examples. Also moved some things around in the readme

docs: Add examples and table of contents

---

fixtures/output/small-secret2.yaml
pkg/kube/template.go
pkg/kube/template_test.go

Change `secretData` to `stringData`
**Fixes:** #69 

fix: Change secretData to stringData

---

Makefile
README.md
version/version.go

chore: Update version to 0.4.1

---

README.md
pkg/auth/vault/kubernetes.go
pkg/auth/vault/kubernetes_test.go
pkg/config/config.go
pkg/config/config_test.go

Support kuberernetes authentication
Note: Does not include a test. Will need to spend more time to figure out testing github and kubernetes auth
**Fixes:** #50 

feat: Support Kubernetes auth

---

README.md
manifests/argocd-cm.yaml
manifests/argocd-repo-server-deploy.yaml
manifests/kustomization.yaml
patch.yaml

Add a kustomize app to easily install argocd with the plugin 

docs: Add kustomize app to easily spin up argocd with plugin

---

README.md
pkg/config/config.go
pkg/config/config_test.go

Add support for [Vault Namespaces](https://www.vaultproject.io/docs/enterprise/namespaces)
**Fixes:** #68 

feat: Support Vault Namespace

---

pkg/backends/ibmsecretmanager.go
pkg/helpers/test_helpers.go

fix: Add check for empty map in secret manager logic

---

README.md
manifests/argocd-cm.yaml

Include documentation on how to use Kustomize with the plugin and add the example to the argocd-cm patch in manifests

feat: Add kustomize to argocd-cm kustomize patch

---

.github/workflows/codeql.yml
README.md
cmd/generate.go
pkg/config/config.go
pkg/config/config_test.go
pkg/utils/util.go

Add support for the Vault environment variables cacert, capath and skip verify
**Fixes:** #52 

feat: Add support for cacert, capath and skip verify variables

---

README.md
pkg/config/config.go
pkg/config/config_test.go

Make Kubernetes Auth Mount Path optional

feat: Make k8s mount path optional

---

Makefile
README.md
version/version.go

chore: bump version to 0.5.0

---

cmd/generate.go
fixtures/input/nonempty/excluded.yaml

**Fixes:** https://github.com/IBM/argocd-vault-plugin/issues/88
Includes yaml to test against at fixtures/input/nonempty/excluded.yaml

fix: skip empty manifests

---

CHANGELOG.md
Makefile
README.md
version/version.go

chore: Bump version to 0.5.1

---

.github/workflows/pipeline.yml
Makefile
README.md
cmd/generate.go
cmd/generate_test.go
cmd/util.go
pkg/config/config.go
pkg/config/config_test.go
version/version.go

Support all vault env vars instead of specific ones
**Fixes:** #85 

feat: Use default vault environment variables

---

CHANGELOG.md
Makefile
README.md
version/version.go

chore: Bump version to 0.7.0

---

README.md

Add note in documentation for TokenReview API access for Service Account
**Fixes:** #102 
- x] Docs have been added / updated

docs: Add note about service account needing TokenReview access

---

README.md
cmd/generate.go
cmd/generate_test.go
examples/annotation-example.yaml
examples/kv-version.yaml
fixtures/input/nonempty/deployment.yaml
fixtures/input/nonempty/full.yaml
fixtures/input/nonempty/ignored-secret.yaml
fixtures/input/nonempty/secret.yaml
fixtures/input/nonempty/secret_path.yaml
fixtures/output/all.yaml
fixtures/output/ignored-secret.yaml
fixtures/output/small-configmap.yaml
fixtures/output/small-cronjob.yaml
fixtures/output/small-deployment.yaml
fixtures/output/small-ingress.yaml
fixtures/output/small-job.yaml
fixtures/output/small-secret.yaml
fixtures/output/small-secret2.yaml
fixtures/output/small-secret3.yaml
fixtures/output/small-secret4.yaml
fixtures/output/small-service.yaml
pkg/backends/vault.go
pkg/backends/vault_test.go
pkg/kube/template.go
pkg/kube/template_test.go
pkg/types/constants.go

Update annotations to follow kubernetes annotation convention 
**Fixes:** #112 

feat: Update annotations to use kubernetes convention

---

CHANGELOG.md
Makefile
version/version.go

chore: bump version to 0.7.1

---

.gitignore
README.md
cmd/generate.go
cmd/generate_test.go
cmd/util.go
fixtures/input/invalid.yaml
fixtures/output/stdin-full.yaml

PR to address feature change requested in https://github.com/IBM/argocd-vault-plugin/issues/116.
Open to suggestions/review!
**Fixes:** 
https://github.com/IBM/argocd-vault-plugin/issues/116

feat: allow objects to be passed from STDIN.

---

README.md
pkg/config/config.go

Still had a reference to `AVP_AWS_REGION`, added aws region to readme under aws section

fix: Set proper aws default region

---

CHANGELOG.md
README.md
version/version.go

chore: bump version to 1.1.0

---

manifests/argocd-repo-server-deploy.yaml

This resolves #125 and also fixes the commands in the manifest example as the newlines were broken when I tried to use the manifest example. This is has been tested in my private team cluster.
**Fixes:** #125 
- [ x The commit message follows the [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0/#summary).
N/A

chore: resolves #125 and fixes broken command arg

---

README.md

Just changing the init container commands to be correct based on latest PR, I should have included this changes as well.
**Fixes:** No issue created, can create one if desired. Let me know...
N/A

fix: corrected init containter ref

---

CHANGELOG.md
Makefile
README.md
manifests/argocd-repo-server-deploy.yaml
version/version.go

chore: bump version to 1.1.1

---

README.md

docs: Add downloads badge to README

---

docs/config.md
fixtures/input/nonempty/secret_remove_missing.yaml
fixtures/output/all.yaml
fixtures/output/secret-remove-missing.yaml
pkg/kube/template.go
pkg/kube/template_test.go
pkg/kube/util.go
pkg/kube/util_test.go
pkg/types/constants.go

PR to address feature change requested in #165.
Open to suggestions/review!

feat: add allow-empty annotation.

---

docs/backends.md

Add examples to the docs for each backend type

docs: Add examples to backends

---

docs/backends.md
docs/config.md
fixtures/input/gac.json
go.mod
pkg/backends/gcpsecretmanager.go
pkg/backends/gcpsecretmanager_test.go
pkg/config/config.go
pkg/config/config_test.go
pkg/types/constants.go

Add GCP Secret Manager as a new backend

feat: Add support for GCP Secret Manager

---

README.md

docs: add new blog post to readme

---

.chglog/config.yml

Currently the release notes generator cant handle scope for conventional commits

ci: update changlelog config to accept scope in commit

---

docs/backends.md
go.mod
go.sum
pkg/backends/azurekeyvault.go
pkg/backends/azurekeyvault_test.go
pkg/config/config.go
pkg/config/config_test.go
pkg/types/constants.go

Add Azure Key Vault as new backend

feat: Add support for Azure Key Vault

---

.github/stale.yml

chore: add a stale config

---

.github/workflows/mkdocs.yml
docs/_overrides/main.html
mkdocs.yml

Version docs via `mike`. Creates 2 moving aliases: `latest`, for the main branch of docs, and `stable` for the latest tagged release. Versions are published and aliases are updated on tag push/main push. Aliases are used off the GH pages URL to redirect to the version they point to.
Live example: https://jkayani.github.io/argocd-vault-plugin/
**Fixes:** #194 

ci: Versioned docs via mike

---

.github/PULL_REQUEST_TEMPLATE.md
USERS.md

Add users list and section to pull request template about adding organization to users list

docs: add users list

---

docs/compatibility.md
mkdocs.yml

Adds a compatibility matrix to our docs so that people know which versions of Kubernetes and Argo CD this has been tested on. 

docs: Add compatibility matrix

---

USERS.md

Add Orange Pikeo project to user list

Update USERS.md to add Orange Pikeo project

---

.readthedocs.yml
docs/requirements.txt

docs: add readthedocs yml and requirements for material

---

docs/assets/versions.css

Fix an issue with versions not showing on mobile

docs: fix versions not showing on mobile

---

README.md

Update readme to use readthedocs url

docs: change docs link to readthedocs

---

.github/workflows/pipeline.yml

ci: add push event back to pipeline workflow

---

cmd/generate.go
docs/config.md
pkg/kube/client.go
pkg/kube/util.go
pkg/kube/util_test.go
pkg/types/constants.go

Support for specifying the namespace containing the configuration secret using the format `<namespace>:<name>`

feat: Support for secret namespace

---

USERS.md

Add Everly Health to list of users

docs: add everly health to users list

---

CONTRIBUTING.md
pkg/kube/client.go

After a recent PR there was a change needed in the comments of `pkg/kube/client.go` around the new `secretNamespaceName` function in `pkg/kube/util.go`.
Also a small typo fix in `CONTRIBUTING.md`

docs: Minor update to Go comments and CONTRIBUTING.md

---

docs/howitworks.md

The documentation contains wrong usage of remove-missing annotation.
It must be quoted. In another way this annotation is ignored.

fix: minor changes in docs

---

.github/workflows/release.yml

Looks I forgot about this when moving everything else to go 1.17

chore: Use go 1.17 for release automation

---

docs/backends.md
docs/config.md
docs/installation.md
examples/annotation-example.yaml
examples/inline-path-placeholder.yaml
examples/path-prefix.yaml
manifests/argocd-cm.yaml
manifests/argocd-repo-server-deploy.yaml

Tries to improve the docs based on feedback and other issues opened. Updates the version numbers in the manifests. 
**Fixes:** #267 

docs: Improve installation docs

---

mkdocs.yml

Fix edit_uri in mkdocs.yaml where it defaults to master.
**Fixes:** https://github.com/argoproj-labs/argocd-vault-plugin/issues/290

fix: Fix edit .md in mkdocs

---

USERS.md

Add Boozt to users.
Add Boozt to users.

docs: Boozt added to users

---

Dockerfile

Update CI golang image to latest 1.17 to avoid CVE-2022-23806

ci: Update to patched go 1.17

---

docs/usage.md

Add a note to the helm docs about the dangers of malicious command injection for example

docs: add note about command injection for helm example

---

.github/workflows/pipeline.yml
.github/workflows/release.yml
Dockerfile

Address https://github.com/advisories/GHSA-6685-ffxp-xm6f
**Fixes:** https://github.com/advisories/GHSA-6685-ffxp-xm6f

ci: Update golang to 1.17.8

---

docs/howitworks.md

docs: Fix typo in docs

---

USERS.md

Adding Aveniq as a user of the software and removing trivia from USERS.md.
**Related:** #221 
* Aveniq is added to the list of users
* USERS.md has been changed to a bullet point list, rather a numeric order, as the order is lexicographic
* The wording «the following organizations are **officially** using argocd-vault-plugin» has been changed to «the following organizations are using argocd-vault-plugin», as the expression «**officially**» is unnecessary as there can not be made a difference between official and unofficial unless those organizations make a public statement by their legal representatives eg. press releases, owners public statements or executives public statements.

docs(USERS.md): Add Aveniq user and remove trivia

---

docs/backends.md
go.mod
go.sum
pkg/auth/vault/userpass.go
pkg/auth/vault/userpass_test.go
pkg/config/config.go
pkg/config/config_test.go
pkg/helpers/test_helpers.go
pkg/types/constants.go

Added support for Vault Userpass auth method & updated relevant documentation.
**Fixes:** #357 #387 
N/A

Add Support for Vault Userpass Auth Method

---

.github/dependabot.yml

Dependabot will create PRs automatically
**Fixes:** NA

ci: update GitHub actions with dependabot

---

docs/usage.md
manifests/cmp-configmap/argocd-cm.yaml
manifests/cmp-sidecar/cmp-plugin.yaml

docs: note security risks of $helm_args

---

docs/installation.md

Signed-off-by: Michael Crenshaw <350466+crenshaw-dev@users.noreply.github.com>

docs: add note about securing Redis and repo-server

---

docs/installation.md
docs/usage.md
manifests/cmp-configmap/argocd-repo-server-deploy.yaml
manifests/cmp-configmap/kustomization.yaml
manifests/cmp-sidecar/argocd-repo-server.yaml
manifests/cmp-sidecar/cmp-plugin.yaml
manifests/cmp-sidecar/kustomization.yaml

chore: prepare for 1.15.0 release
