- fixtures/output/small-configmap.yaml
- pkg/kube/configmap.go
- pkg/kube/configmap_test.go
- pkg/kube/deployment.go
- pkg/kube/secret.go
- pkg/kube/template.go
- pkg/kube/template_test.go
- pkg/kube/util.go
- Adds support for templated `ConfigMap` YAMLs
- Moves `CreateTemplate()` from util.go to template.go since that makes more sense and clearly shows what kinds of Templates we currently support
- Deduplicate code to decode a replaced template into a Kubernetes resource struct
> feat: Support ConfigMap templates

- cmd/util.go
- fixtures/input/nonempty/full.yaml
- fixtures/output/small-service.yaml
- pkg/kube/service.go
- pkg/kube/template.go
- pkg/kube/template_test.go
- pkg/kube/util.go
Add support for Kubernetes services and multi-doc YAML like this:
```
apiVersion: v1
kind: Service
metadata:
name: <name>
namespace: <namespace>
labels:
app: <name>
spec:
selector:
app: <name>
ports:
- protocol: TCP
name: http
port: 80
targetPort: <target-port>
type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: <name>
namespace: <namespace>
labels:
app: <name>
version: <version>
spec:
selector:
matchLabels:
app: <name>
replicas: <replicas>
strategy:
type: RollingUpdate
rollingUpdate:
maxSurge: 1
maxUnavailable: 1
minReadySeconds: 5
revisionHistoryLimit: 10
template:
metadata:
name: <name>
labels:
app: <name>
spec:
containers:
- name: <name>
image: foo.com/<name>:<tag>
imagePullPolicy: Always
```
- Refactors the resource decode function to not need to guess if YAML or …
> feat: Support for Service resource and multi-document YAML files

- pkg/vault/util.go
- pkg/vault/utils_test.go
- version/version.go
Fix issue with token not being set if writing config fails
**Fixes:** #38 
> fix: Set token before writing to file, silent fail if error

- fixtures/output/small-secret2.yaml
- fixtures/output/small-secret3.yaml
- fixtures/output/small-secret4.yaml
- pkg/kube/template.go
- pkg/kube/template_test.go
- pkg/kube/util.go
Previously, the plugin would attempt to always get secrets from Vault for each manifest, even if there were no secrets in Vault for it. Now, the logic is as follows:
- If there are placeholders in the manifest template, try to get secrets from Vault, and return any appropriate error during that and during replacement
- Otherwise, skip reading from Vault, and emit the manifest as-is during replacement
Fixing this also introduced a new problem with `Secret`'s, since things under `data` need to be in base64 format, whereas everything else doesn't. So we add the following logic:
- If a `Secret.data` key has a `<placeholder>` value, we emit it's replacement base64 encoded. The expectation therefore is that the user puts data into Vault exactly as they want it loaded _into their app_
- …
> fix: Handle YAMLs with non-placeholder strings properly

- pkg/config/config.go
When the K8sAuth struct is constructed in config.go, the arguments passed to NewK8sAuth for K8S_ROLE and K8S_MOUNT_POINT has been seemingly accidentally reversed.
This PR swaps them, so that they are passed in the correct order.
> fixed k8s authtype reversed args

- pkg/utils/util.go
Increase the timeout for the DefaultHttpClient to 60s.
**Fixes:** https://github.com/IBM/argocd-vault-plugin/issues/97
> fix: Increase timeout on DefaultHttpClient to 60s

- fixtures/output/small-custom-resource.yaml
- pkg/kube/template_test.go
- pkg/kube/util.go
- Removes unnecessary panics by skipping over any YAML nodes that are ineligible for replacement; i.e, anything that is not a `[]string`, `map[string]interface{}`, or `string`
**Fixes:** #63 
> fix: Remove unnecessary panics on replace

- go.mod
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/kube/template.go
- pkg/kube/template_test.go
Fixes the other problems discovered in testing #115:
- Sets `VAULT_` variables from Viper-read config file or k8s secret
- Prints the replacement errors newline separated to make them easier to read
> fix: Set VAULT_ variables from Viper and display replace errors better

- fixtures/input/nonempty/secret_path_base64.yaml
- fixtures/output/all.yaml
- pkg/kube/template.go
- pkg/kube/util.go
- pkg/kube/util_test.go
Checks if secret placeholders are base64 encoded before replacing.
**Fixes:** https://github.com/IBM/argocd-vault-plugin/issues/124
I'm open to suggestions on how to document this.
> feat: decode base64 encoded placeholders in secrets

- README.md
- fixtures/output/small-custom-resource-fake-placeholders.yaml
- pkg/helpers/test_helpers.go
- pkg/kube/template_test.go
- pkg/kube/util.go
- pkg/kube/util_test.go
Currently AVP works by reading the path from either the path annotation (`avp.kubernetes.io/path`) or from the specific path set in each placeholder (`<path:somewhere#some-key>`). 
In YAML files where there is no path annotation set, AVP can only work if all placeholders are in the specific path syntax. Therefore, we can make AVP "smarter" by having it ignore generic placeholders of the form `<placeholder>` if the path annotation is missing, since they can't be replaced anyway. This prevents users from having to add ignore annotations to YAMLs that will never contain intentional placeholders, like CRDs. Credits to @llavaud for the idea. 
**Fixes:** #130 
> feat: Skip <string>'s with absence of path annotation

- README.md
- pkg/config/config_test.go
- pkg/types/constants.go
For AWS secrets manager, we have to use the aws defined env vars without the `AVP` prefix.
**Fixes:** #133 #131 
Also added `k8s` as a valid auth type to the supported parameters table
> fix: remove avp prefix from aws env vars

- README.md
- fixtures/input/nonempty/secret_path_base64.yaml
- fixtures/input/nonempty/secret_path_base64_substring.yaml
- fixtures/output/all.yaml
- pkg/helpers/test_helpers.go
- pkg/kube/util.go
- pkg/kube/util_test.go
If a secret is successfully decoded from base64, assume it needs to be re-encoded.  This allows for secret values with multiple placeholders or concatenation with other strings. 
**Fixes:** https://github.com/IBM/argocd-vault-plugin/issues/124
> fix: implicitly base64 encode base64 secret values

- README.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/types/constants.go
Enforcing the specification of the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` env variables blocks other authentication methods supported by the AWS go SDK from being used by argocd-vault-plugin. Even within env vars authentication, there exist other options than just `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`: e.g. using an assumed role on ec2/EKS. This PR removes the unnecessary check for the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` env vars. It does remain recommended to set the proper AWS region via an environment variables however. 
**Fixes:** https://github.com/IBM/argocd-vault-plugin/issues/148
Note, this PR was tested successfully with an IAM role for service accounts as the auth method on an AWS …
> fix: env variables check blocks many AWS authentication methods 

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/types/constants.go
Issue a warning to inform the user that (s)he forget to set `AWS_REGION` and that the default region will be used.
Note this PR is blocked by PR #151.
**Fixes:** https://github.com/IBM/argocd-vault-plugin/issues/154
> fix: issue warning when default aws region is used

- .chglog/CHANGELOG.tpl.md
- .chglog/config.yml
- .github/workflows/release.yml
- .gitignore
- .goreleaser.yaml
- Makefile
- cmd/version.go
- cmd/version_test.go
- version/version.go
Add release automation via pushing a semvar Tag
Example Release:
https://github.com/werne2j/argocd-vault-plugin/releases/tag/v1.1.2
**Fixes:** #14
Thanks to @teejaded for getting this work started!
> ci: add release automation

- fixtures/input/nonempty/secret_embedded_base64.yaml
- fixtures/output/all.yaml
- pkg/kube/template.go
- pkg/kube/util.go
- pkg/kube/util_test.go
Fixes an issue where if the bas64 modifier is included in a longer string it was replacing the entire string
**Fixes:** #162 
> fix: dont replace entire string if base64 modifier included

- README.md
The application name of the Argo CD maps to Helm Chart's Relase Name.
When ArgoCD sync, environment varivable  "ARGOCD_APP_NAME" set ArgoCD  application name
[Argocd Docs](https://argoproj.github.io/argo-cd/user-guide/helm/#helm-release-name)
if ArgoCD application name is "certificate-exporter"
before(use `helm template . > all.yaml`)
RELEASE-NAME-x509-certificate-exporter-headless
after(use `helm template $ARGOCD_APP_NAME . > all.yaml`)
certificate-exporter-x509-certificate-exporter-headless
> docs: update argocd-cm plugin setting

- cmd/generate.go
- cmd/generate_test.go
- cmd/util.go
- docs/howitworks.md
- docs/installation.md
- fixtures/input/nonempty/secret.json
- fixtures/output/all.yaml
Adds support for JSON files as input. Since ArgoCD plugins _must_ generate YAML output (https://argoproj.github.io/argo-cd/user-guide/config-management-plugins/#plugins), the JSON is replaced and then output as YAML. 
**Fixes:** #181 
> feat: Support JSON manifests

- .github/workflows/pipeline.yml
- Dockerfile
- Makefile
Dockerize the CI environment on Linux to avoid this problem: https://github.com/IBM/argocd-vault-plugin/pull/193#issuecomment-911876575. 
This solution works based on this Actions run https://github.com/IBM/argocd-vault-plugin/runs/3508366010?check_suite_focus=true which makes these changes atop PR 193 to prove we avoid the special-case of Azure auth solely via cloud-provider metadata endpoints
Specific CI changes:
- Split the CI matrix since we use Docker on Linux not on Mac
- Add a Dockerfile that downloads the Golang deps at build time
- Run `go vet` only on our code (nor our deps) and run `go test` in a network isolated container to avoid successful Azure auth
- Upload code coverage only once
- Remove some un-used stuff from the Makefile
Please make sure that your PR fulfills the …
> ci: Use Docker for CI on Linux

- docs/installation.md
This change should make the 2 links in https://ibm.github.io/argocd-vault-plugin/installation/ clickable.
> docs: make links clickable

- pkg/backends/awssecretsmanager.go
- pkg/backends/awssecretsmanager_test.go
- pkg/types/constants.go
Don't use `AWSCURRENT` as a value for `VersionId` when no version is specified: instead just omit the field entirely
**Fixes:** #199 
> fix(aws): Omit versionId unless specified

- 404.html
Adds 404 page that will redirect to `/stable/<rest of path>` so that old links like https://ibm.github.io/argocd-vault-plugin/installation/#custom-image will work
Proof it works: <https://jkayani.github.io/argocd-vault-plugin/installation/#custom-image>
> docs: Redirect old docs to stable

- docs/_overrides/main.html
Hide banner if not browsing main docs. Need to regenerate all previously generated docs again.
Script to regenerate previous docs:
```sh
git checkout gh-pages
git rm -rf main/ preview/ stable/ v1.*/ index.html versions.json
git commit -m "docs: Cleanup existing docs"
tags=( "v1.2.0" "v1.3.0" "v1.3.1" )
for tag in "${tags[@]}"
do
git checkout $tag --force
git cherry-pick a58845efdaaf4202b7238fc4b80c8b637cdc96b6
git cherry-pick theme-fix
mike deploy -u $tag stable
done
mike set-default stable
git push --force origin gh-pages:gh-pages
```
Script tested here: https://github.com/jkayani/argocd-vault-plugin/tree/gh-pages
> docs: Hide banner if not browsing main docs

- pkg/backends/ibmsecretsmanager.go
- pkg/backends/ibmsecretsmanager_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/types/constants.go
Uses goroutines to have 20 concurrent requests to the IBM SM API at any given time, so that we are able to retrieve the payloads for all secrets in a group faster. Previously we were retrieving them sequentially. To avoid rate limit problems, the IBM SM SDK is instantiated with a setting to do 3 retries, 20 second apart for each request. 
Also handles pagination in IBM SM - [a group with more than 200 secrets requires additional API calls to get the rest](https://cloud.ibm.com/apidocs/secrets-manager#list-all-secrets-request). Logic is added to AVP to handle this. 
**Partially addresses:** #207 
> perf(ibmsecretsmanager): Get secrets concurrently

- docs/backends.md
- pkg/backends/awssecretsmanager.go
- pkg/backends/awssecretsmanager_test.go
- pkg/backends/azurekeyvault.go
- pkg/backends/azurekeyvault_test.go
- pkg/backends/gcpsecretmanager.go
- pkg/backends/gcpsecretmanager_test.go
- pkg/backends/ibmsecretsmanager.go
- pkg/backends/ibmsecretsmanager_test.go
- pkg/backends/vault.go
- pkg/backends/vault_test.go
- pkg/config/config.go
- pkg/helpers/test_helpers.go
- pkg/kube/util.go
- pkg/kube/util_test.go
- pkg/types/types.go
As discussed in https://github.com/IBM/argocd-vault-plugin/issues/207#issuecomment-926098403, we add a new method to the backend interface so that SM backends that can address individual secrets (placeholders) like Azure can be sped up considerably when using inline-path placeholders. Backends that cannot do this just call `GetSecrets` and return the single value from the k/v pair, just like what was done previously. 
Also forward config keys prefixed with `azure` and `google` to the corresponding SDK for making auth easier.
**Fixes:** #207 
> refactor: Add GetIndividualSecret method to backends

- pkg/backends/ibmsecretsmanager.go
- pkg/backends/ibmsecretsmanager_test.go
Add caching of data in the IBM SM backend so that secrets are replaced faster. I started with this one in particular because it performs the worst: for each manifest, to replace a placeholder, the ID of the secret corresponding to that placeholder has to be retrieved and only then can the secret payload be obtained. Obtaining the payloads is currently done by getting the payloads of _all_ the secrets in a group, and filtering as needed, for _every_ inline-path placeholder. Lots of room for improvement.
The idea is to cache all API call results within an invocation of the plugin. Since every invocation of the plugin uses a specific backend configuration and we use the same backend for replacing each template, we can cache results across manifests, and across placeholders within a manifest. …
> feat: Cache data from IBM SM within invocation

- pkg/kube/client.go
Fix of -s do not parse secret name/namespace properly. The variables were misplaced from function return.
**Fixes:** #287 
> fix: -s do parse secret name/namespace properly

- docs/config.md
- pkg/auth/vault/approle.go
- pkg/auth/vault/approle_test.go
- pkg/auth/vault/github.go
- pkg/auth/vault/github_test.go
- pkg/auth/vault/kubernetes.go
- pkg/backends/vault_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/types/constants.go
Add a configuration key `AVP_MOUNT_PATH` that can be used to provide the path to auth to Vault (a generic form of `AVP_K8S_MOUNT_PATH`). 
**Fixes:** #272 
> feat: Support user-supplied Vault auth paths

- docs/usage.md
- manifests/argocd-cm.yaml
This adds documentation on how to use argocd-vault-plugin with Helm values inline in the ArgoCD application manifest (similar to the `--values-literal-file` option or declarative setup here https://github.com/argoproj/argo-cd/blob/cd497c4eec84a47040816a0b04361005c3ce0ee8/docs/operator-manual/application.yaml#L39-L52).
I also changed the example argocd-cm.yml manifest to include `$ARGOCD_APP_NAME` to match the examples from the docs.
**Fixes:** https://github.com/argoproj-labs/argocd-vault-plugin/issues/304 and also https://github.com/argoproj-labs/argocd-vault-plugin/issues/266 (but only for the CLI workflow).
> docs: how to use inline Helm values in ArgoCD manifests

- docs/usage.md
Update helm plugin usage to include install-crds bringing it inline with default ArgoCD helm behaviour (ArgoCD defaults to setting install-crds) 
See: https://github.com/argoproj/argo-cd/pull/3345
Currently the AVP usage documentation includes a code snippet for how to register the AVP plugin for helm. The used helm template command does not include the flag --install-crds, resulting in ArgoCD helm deployments using AVP not installing CRDs.
This deviates from the ArgoCD default behavior which had this flag specifically added in [PR 3345](https://github.com/argoproj/argo-cd/pull/3345).
> docs: update helm usage

- docs/backends.md
- docs/config.md
- go.mod
- go.sum
- pkg/backends/onepasswordconnect.go
- pkg/backends/onepasswordconnect_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/types/constants.go
Add support for 1Password Connect servers as a backend
**Fixes:** #235
> feat: Support 1Password Connect as a backend

- docs/config.md
- docs/howitworks.md
- **modifiers**: link starting with a capital letter only works on GitHub Markdown - not within readthedocs.io
- **backends**: link with single dot will not forward to page on readthedocs.io
_(tested with `Chrome, Windows`, `Firefox, Ubuntu`)_
This PR change will only fix two hyperlink.
**Fixes:**
- fix hyperlink (anker) on same page to Modifiers - using lower case
- fix hyperlink to backends page - using two dots as [already](https://github.com/argoproj-labs/argocd-vault-plugin/blob/b434368a10e088add8c47e0a8be0a003376436a8/docs/installation.md?plain=1#L116) in use
> docs: fix modifiers link

- docs/installation.md
Best practice is to stick with same user (id) as [argoproj/argo-cd](https://github.com/argoproj/argo-cd/blob/f90514587bafcce51e0e2cd6044195fed2266707/Dockerfile#L130).
The example in the documentation will change the user to a name instead of id.
The user still remains the same.
This helps to verify if user runs with securityContext (otherwise it could fail):
```yaml
securityContext:
runAsUser: 999
```
> docs: use same user in Dockerfile as argocd image

- docs/backends.md
Addition of some examples of usage for cross account stored secrets on AWS Secrets Manager.
The ARN of the secret can be used in this case. Permissions on IAM roles and KMS keys are needed to configure the cross account access, links added
**Fixes:**
Existent examples were vault examples:
https://github.com/argoproj-labs/argocd-vault-plugin/issues/316
> Docs - Add examples for aws secrets manager

- .goreleaser.yaml
- docs/installation.md
Signed-off-by: skuethe <56306041+skuethe@users.noreply.github.com>
Adding `s390x` to goreleaser, so that the binary can be used on zLinux systems.
**Fixes:** #327
> feat: add s390x builds on release

- docs/config.md
Fixing documentation typo of "above" to be "below" when describing where the keys you can find are.
**Fixes:** there was no issue for this.
This is a really simple doc fix.
> Fix: documentation typo from "above" to "below" for key location

- .github/ISSUE_TEMPLATE/bug_report.md
- cmd/generate.go
- docs/cmd/generate.md
- pkg/auth/vault/approle.go
- pkg/auth/vault/github.go
- pkg/auth/vault/kubernetes.go
- pkg/backends/awssecretsmanager.go
- pkg/backends/azurekeyvault.go
- pkg/backends/gcpsecretmanager.go
- pkg/backends/ibmsecretsmanager.go
- pkg/backends/localsecretmanager.go
- pkg/backends/onepasswordconnect.go
- pkg/backends/vault.go
- pkg/backends/yandexcloudlockbox.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/kube/client.go
- pkg/kube/template.go
- pkg/kube/util.go
- pkg/utils/util.go
Adds a verbose output flag so that users can troubleshoot AVP usage easier. Goal is to be able to trace:
- The final configuration Viper sees
- The processing being done for each placeholder
- API calls and responses from backends for both authentication and getting secrets
Assuming this looks worthwhile, I think it'd be good for bug reports to include this info to help us debug what's happening. This PR amends the issue template to say that.
**Fixes:** #307 
> feat: Verbose logging with flag

- docs/config.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/types/constants.go
ArgoCD 2.4 adds a security fix where all environment variables passed to the repo server during the `init` and `generate` phases are prefixed with `ARGOCD_ENV` to prevent users from setting potentially sensitive environment variables. The `argocd-vault-plugin` binary needs to read the required values from env vars with the new prefix. This PR adds another flag to set (`USE_PREFIX`) to switch from reading un-prefixed to reading prefixed env vars.
- [ X] Reviewed the guidelines for contributing to this repository
- [ X] Tests for the changes have been updated
- [ X] Docs have been added / updated
- [ X] Feature
- [ X] Documentation content changes
The ArgoCD 2.4 breaking change was mentioned in #352. I tried looking into …
> feat: Add compatibility for ArgoCD 2.4 prefixed environment variables

- manifests/cmp-sidecar/argocd-repo-server.yaml
- manifests/cmp-sidecar/kustomization.yaml
This allows us to avoid having to manage the versions for helm & kustomize
alongside AVP and argocd, as these binaries are included in the argocd image.
We can add a kustomize images entry to specify / modify the image version from
the kustomization.yaml file.
**Fixes:** #368
This is intended to be a draft PR just to illustrate my thought in #368. If the maintainers like it I can make it into an actual PR.
> feat: Use argocd image for sidecar

- cmd/generate.go
- cmd/generate_test.go
- docs/howitworks.md
Removes the if statement to check if manifests are empty and updates the test accordingly
**Fixes:**
#363
> Empty manifests should result in empty output

- manifests/cmp-configmap/argocd-cm.yaml
Change env variable `HELM_VALUES` to `ARGOCD_ENV_HELM_VALUES` in
manifest to comply with (#356) changes
Add `-n "$ARGOCD_APP_NAMESPACE"` to use with `helm template` to avoid
issues with with `{{.Release.Namespace}}` in helm templates
There are two issues I encountered when using configmap manifests.
* One is, usage of old env variable name, fixed in #356 
* Second is, not forwarding argocd's application destination namespace to helm.
If helm chart uses `{{.Release.Namespace}}` then deployment uses my argocd namespace, ignoring application configuration.
It can be easily avoided by explicitly forwarding namespace from environmental variables.
`helm template -n "$ARGOCD_APP_NAMESPACE"`
**Fixes:** Documentation.
I assume that …
> docs: update argocd-cm manifest

- docs/backends.md
The link was broken because it linked to the GitHub repo:
`https://github.com/argoproj-labs/argocd-vault-plugin/blob/v1.12.0/docs/vaultproject.io/docs/auth/kubernetes#configuration`
> docs: fix typo in url to vault k8s auth

- docs/usage.md
The example that shows how avp can be invoked to render with the cm configmap has been updated to:
- include the added prefix in env vars (https://argocd-vault-plugin.readthedocs.io/en/stable/config/#argocd-240-environment-variable-prefix)
- respect the namespace of the application
> Add the ARGOCD_ENV prefix in the helm with args example

- cmd/generate.go
- cmd/generate_test.go
- docs/config.md
- pkg/kube/template.go
- pkg/kube/template_test.go
- pkg/kube/util.go
- pkg/kube/util_test.go
- pkg/types/constants.go
Users should have the ability to additionally validate vault paths. For example to prevent path traversals.
This can be enabled by setting a regular expression to the new environment variable `AVP_PATH_VALIDATION`.
This pull requests relates to the issue https://github.com/argoproj-labs/argocd-vault-plugin/issues/418.
> feat: add vault-path validation

- docs/usage.md
The CMP-managed plugin documentation for using Helm values was still using a non `ARGOCD_ENV_` prefixed environment variable setup which only works on ArgoCD version before 2.4. This change adds the prefix in the corresponding code examples.
> docs: Update plugin usage documentation

- manifests/cmp-configmap/argocd-repo-server-deploy.yaml
- manifests/cmp-sidecar/argocd-repo-server.yaml
- pkg/backends/awssecretsmanager.go
Add support for AWSCURRENT and AWSPREVIOUS
**Fixes:** #453
> fix(aws): support for version stage

- pkg/auth/vault/approle.go
Add mount path to verbose logging for approle
> chore: add mount path to verbose logging for approle

- USERS.md
> docs: Add Close to the users

- docs/backends.md
- pkg/backends/awssecretsmanager.go
- pkg/backends/awssecretsmanager_test.go
We use `SecretBinary` has key part to retreive binary data from AWS Secrets Manager.
**Fixes:** https://github.com/argoproj-labs/argocd-vault-plugin/issues/499
> feat(awssecrets): add support for binary

- docs/installation.md
- manifests/cmp-configmap/argocd-repo-server-deploy.yaml
- manifests/cmp-configmap/kustomization.yaml
- manifests/cmp-sidecar/argocd-repo-server.yaml
- manifests/cmp-sidecar/kustomization.yaml
**Fixes:** https://github.com/argoproj-labs/argocd-vault-plugin/issues/516
Releases:  
* https://github.com/argoproj-labs/argocd-vault-plugin/pull/521 
* package updates
- [x ] Reviewed the guidelines for contributing to this repository
- [x ] The commit message follows the [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [x ] Docs have been added / updated
- [ x] Documentation content changes
> chore: prepare for 1.16.0 release

- pkg/backends/ibmsecretsmanager.go
- pkg/backends/ibmsecretsmanager_test.go
After #517 , AVP was not handling KV secrets correctly, leaving the KV pairs of a `kv` secret in the `data` key of the returned secret's JSON instead of extracting them for individual interpolation like before. This PR restores the original behavior.
A test case was added to verify this issue (fails on `HEAD`) and I've verified in an e2e test that this appears to be fix the issue
**Fixes:** #534 
> fix(ibmsm): Copy keys from KV types

- pkg/auth/vault/approle.go
- pkg/auth/vault/approle_test.go
- pkg/auth/vault/github.go
- pkg/auth/vault/github_test.go
- pkg/auth/vault/kubernetes.go
- pkg/auth/vault/kubernetes_test.go
- pkg/auth/vault/userpass.go
- pkg/auth/vault/userpass_test.go
- pkg/utils/util.go
- pkg/utils/utils_test.go
This commit adds the check of the cached vault token before doing the authentication flow over again
**Fixes:** <https://github.com/argoproj-labs/argocd-vault-plugin/issues/536>
> fix: look for vault cached token before login

- go.mod
- go.sum
- pkg/backends/azurekeyvault.go
- pkg/backends/azurekeyvault_test.go
- pkg/config/config.go
- pkg/config/config_test.go
Add support for Azure AD Workload Identity. 
https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview
Replace low level Azure mod _**autorest**_ that is deprecated by more higth level Azure Api
https://github.com/Azure/go-autorest/blob/autorest/azure/auth/v0.5.12/README.md
**Replace old PR:** 
- https://github.com/argoproj-labs/argocd-vault-plugin/pull/425
**Fixes:**  
- https://github.com/argoproj-labs/argocd-vault-plugin/issues/421
- https://github.com/argoproj-labs/argocd-vault-plugin/issues/539
Update Go from 17 to 18 because new tests required Go 18 as Azure function use generic
> Add support for Azure AD Workload Identity.
